- name: System Health Check
  hosts: all
  tasks:
    - name: Ensure docker is running
      service:
        name: docker  # Or the name of your web service
        state: started

    - name: Ensure database service is running
      service:
        name: mysql  # Or the name of your database service
        state: started
